dataset:
  script_path: ../datasets/ohio.py
  xml_path: C:\Users\baiyi\OneDrive\Desktop\new_ReproGen_code\ReproducibilityStudy_DL_BGPrediction\datasets\OhioT1DM\2018\test\559-ws-testing.xml
  nb_past_steps: 12
  param_nb_future_steps: [6]
  train_fraction: 0.0
  valid_fraction: 0.0
  test_fraction: 1.0
  scale: 0.01
model:
  script_path: ../Original_Martinsson/models/lstm_experiment_keras.py
  nb_lstm_states: 256
  activation_function: exp
optimizer:
  script_path: ../Original_Martinsson/optimizers/adam_keras.py
  learning_rate: 1e-3
loss_function:
  script_path: ../Original_Martinsson/loss_functions/nll_keras.py
train:
  script_path: ../Original_Martinsson/train/train_keras.py
  artifacts_path: ../artifacts/all_final_experiment/
  batch_size: 1024
  epochs: 10000
  patience: 200
  shuffle: True
  param_seed: [60]
