dataset:
  script_path: ../datasets/ohio.py
  xml_path: ../../datasets/OhioT1DM/2020/train/all
  nb_past_steps: 12
  param_nb_future_steps: [6]
  train_fraction: 0.8
  valid_fraction: 0.2
  test_fraction: 0
  scale: 0.01
model:
  script_path: ../Original_Martinsson/models/lstm_experiment_keras.py
  nb_lstm_states: 256
  activation_function: exp
optimizer:
  script_path: ../Original_Martinsson/optimizers/adam_keras.py
  learning_rate: 1e-3
loss_function:
  script_path: ../Original_Martinsson/loss_functions/nll_keras.py
train:
  script_path: ../Original_Martinsson/train/train_keras.py
  artifacts_path: ../artifacts/all_final_experiment/
  batch_size: 1024
  epochs: 10000
  patience: 200
  shuffle: True
  param_seed: [10,25,50]