dataset:
  script_path: ../datasets/ohio.py
  xml_path: ../../datasets/OhioT1DM/2020/test/544-ws-testing.xml
  nb_past_steps: 6
  param_nb_future_steps: [6]
  train_fraction: 0.0
  valid_fraction: 0.0
  test_fraction: 1.0
  scale: 0.01
model:
  script_path: ../models/lstm_experiment_keras_vanDoorn.py
  nb_lstm_states: 32
  activation_function: relu
optimizer:
  script_path: ../optimizers/adam_keras.py
  learning_rate: 1e-4
loss_function:
  script_path: ../loss_functions/mse_keras.py
train:
  script_path: ../train/train_keras.py
  artifacts_path: ../artifacts/vandoorn_original_experiment_6sh/
  batch_size: 1024
  epochs: 10000
  patience: 100
  shuffle: True
  param_seed: [10,25,50]