dataset:
  script_path: ../datasets/t1dexi.py
  csv_path: C:/Users/baiyi/OneDrive/Desktop/Modify_GenBG/modified_t1dexi_subset/T1DEXI_cgm_processed/fold1_training/all
  nb_past_steps: 6
  param_nb_future_steps: [6]
  train_fraction: 0.8
  valid_fraction: 0.2
  test_fraction: 0
  scale: 0.01
model:
  script_path: ../Original_vanDoorn/models/lstm_experiment_keras_vanDoorn.py
  nb_lstm_states: 32
  activation_function: relu
optimizer:
  script_path: ../Original_vanDoorn/optimizers/adam_keras.py
  learning_rate: 1e-3
loss_function:
  script_path: ../Original_vanDoorn/loss_functions/mse_keras.py
train:
  script_path: ../Original_vanDoorn/train/train_keras.py
  artifacts_path: ../artifacts/vandoorn_t1dexi_experiment_6sh/
  batch_size: 1024
  epochs: 10000
  patience: 100
  shuffle: True
  param_seed: [20]